### ISSUE TITLE
Implementación Google Analytics o Similares

### ISSUE THREAD

**Issue by sgomezglobant** [sgomezglobant/reactweek#21]
Ya que el sitio es super simple bastaría una implementación secilla de analytics sobre gastby. Sin embargo mientras más podamos aprender de los usuarios a través de analytics mejor.

**Comment by sgomezglobant** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-132930830-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-132930830-1');
</script>

**Comment by Angelfire** [comment]
También podrían revisar esto si lo consideran más sencillo de implementar https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/

**Comment by santidelosrios** [comment]
Hola @sgomezglobant @Angelfire saben si alguien se está encargando de este issue? yo podría cogerlo, quedo atento.

**Comment by Angelfire** [comment]
@santidelosrios Asignatelo, muchas gracias!

**Comment by santidelosrios** [comment]
No me deja asignarmelo, igual o trabajo esta noche!

**Comment by santidelosrios** [comment]
Me tocó realizar una implementación un poco rara, mañana podríamos revisarla y de una vez verificar si se trackean las visitas? @sgomezglobant @Angelfire

**Comment by xkill-9** [comment]
Solucionado por @santidelosrios en #45
