### ISSUE TITLE
Link a página de registro del evento en eventbrite o implementación del widget de registro

### ISSUE THREAD

**Issue by sgomezglobant** [sgomezglobant/reactweek#23]
Ya está la página en eventbrite desde donde se manejará todo el tema de ticketing y entrada al evento, la idea es que en el boton donde diga registrate o bien cargue el widget de eventbrite del evento o bien se redirija a esta página.

https://www.eventbrite.com/e/react-week-medellin-2019-tickets-55239292210
https://react-week-medellin.eventbrite.com

**Comment by JMGR2996** [comment]
Mio

**Comment by xkill-9** [comment]
Esto al fin quedo listo? @JMGR2996

**Comment by JMGR2996** [comment]
Si claro, ya esta integrado incluso @xkill-9

**Comment by xkill-9** [comment]
Ferpecto :B, se cierra entonces
