### ISSUE TITLE
Destacar un poco más el título de las conferencias

### ISSUE THREAD

**Issue by duvan258** [sgomezglobant/reactweek#29]
Pienso que el título como tal de la conferencia, se podría destacar un poco más del resto del texto

![image](https://user-images.githubusercontent.com/4497502/51612571-b8ebf800-1eef-11e9-80c5-2e7f0926f907.png)

**Comment by angelitaooo** [comment]
Yo lo hago :)

**Comment by jotauribe** [comment]
El PR #34 have esto. :)

**Comment by angelitaooo** [comment]
Pueden cerrar este issue si ya lo hicieron?? O le vamos a hacer algun cambio al titulo, yo pensaba que el nombre de la charla se destacara mas que el horario. @jotauribe @Angelfire @sgomezglobant
