### ISSUE TITLE
Sección de speakers 

### ISSUE THREAD

**Issue by sgomezglobant** [sgomezglobant/reactweek#3]
<img width="1624" alt="screen shot 2019-01-18 at 8 09 05 am" src="https://user-images.githubusercontent.com/20705054/51388742-57dfb100-1af8-11e9-87fe-e58c50dde285.png">

**Comment by JMGR2996** [comment]
Hi Sebastian, could you assign this to me?

**Comment by xkill-9** [comment]
Solucionado por @JMGR2996 en #15
