### ISSUE TITLE
Sección Agenda

### ISSUE THREAD

**Issue by sgomezglobant** [sgomezglobant/reactweek#4]
<img width="798" alt="screen shot 2019-01-18 at 8 09 26 am" src="https://user-images.githubusercontent.com/20705054/51388761-65953680-1af8-11e9-8825-dd8bbfdfeb5b.png">

**Comment by angelitaooo** [comment]
Yo puedo trabajar en este.

**Comment by xkill-9** [comment]
Solucionado por @jotauribe en #14
