### ISSUE TITLE
Sección mapa

### ISSUE THREAD

**Issue by sgomezglobant** [sgomezglobant/reactweek#5]
<img width="841" alt="screen shot 2019-01-18 at 8 09 47 am" src="https://user-images.githubusercontent.com/20705054/51388787-72198f00-1af8-11e9-9fc7-d0d6c080a253.png">

**Comment by duvan258** [comment]
Yo realizo esta sección 😄

**Comment by xkill-9** [comment]
Solucionado por @duvan258 en #31
