### ISSUE TITLE
Darle mas visibilidad al botón de registro

### ISSUE THREAD

**Issue by xkill-9** [sgomezglobant/reactweek#58]
## Descripción
El botón de registro debería ser inmediatamente visible para las personas que visiten la página.

Se plantea cambiar el botón de livestream que ahora esta en la cabecera por el botón de registro y encontrar un espacio para el botón de livestream cuando ya se tenga listo.

**Comment by angelitaooo** [comment]
Creo que este ya lo podemos cerrar???? @xkill-9 @sgomezglobant
