### ISSUE TITLE
Sección patrocina y organiza

### ISSUE THREAD

**Issue by sgomezglobant** [sgomezglobant/reactweek#6]
<img width="1573" alt="screen shot 2019-01-18 at 8 10 09 am" src="https://user-images.githubusercontent.com/20705054/51388811-7f367e00-1af8-11e9-93a3-3739858c5dd9.png">

**Comment by santidelosrios** [comment]
Me apunto para este

**Comment by santidelosrios** [comment]
Me apunto para este.

**Comment by xkill-9** [comment]
Solucionado por @santidelosrios en #18
