### ISSUE TITLE
Sección voluntarios

### ISSUE THREAD

**Issue by sgomezglobant** [sgomezglobant/reactweek#7]
<img width="768" alt="screen shot 2019-01-18 at 8 10 29 am" src="https://user-images.githubusercontent.com/20705054/51388828-8fe6f400-1af8-11e9-9443-679170b647e5.png">

**Comment by xkill-9** [comment]
@jodavaga creo la sección voluntarios en #33 entonces voy a darlo por cerrado. 

Voy a crear un nuevo issue solicitando actualizar la info de los voluntarios, somos al menos 11 personas las que hemos contribuido al repo y solo estamos 6.
